spring:
  # configura cor no log do terminal
  output.ansi.enabled: ALWAYS
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  cloud:
    gateway:
      discover:
        locator:
          enabled: true
          lower-case-service-id: true