spring:
  # configura cor no log do terminal
  output.ansi.enabled: ALWAYS
  application:
    name: servidor-eureka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false