spring:
  # configura cor no log do terminal
  output.ansi.enabled: ALWAYS
  application:
    name: ms-funcionario

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: true
  datasource:
    url: jdbc:h2:mem:dbfuncionario
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.pbcompass.apifuncionarios.controller

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,info,loggers"
      base-path: "/gerenciador"
      path-mapping:
        health: "saude"
        metrics: "metricas"
    enabled-by-default: false
  metrics:
    enable:
      executor: false
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always   #never
    metrics:
      enabled: true
    info:
      enabled: true
    auditevents:
      enabled: true
    loggers:
      enabled: true
info:
  application:
    name: ${spring.application.name}
    description: API de Funcionários
