spring:
  application:
    name: ms-funcionario
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:h2:mem:dbfuncionario
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
